### ISSUE TITLE
Sample throws error when using the -t flag for time

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.geospatial#41]
Depends on https://github.com/numenta/nupic/issues/1798.

    python run.py output/sample.csv -t -v

Yields:

```
∙ python run.py output/sample.csv -t
Traceback (most recent call last):
  File "run.py", line 120, in <module>
    not options.manualSequence)
  File "run.py", line 98, in run
    verbose=verbose)
  File "/Users/mtaylor/nta/nupic.geospatial/model/geospatial_anomaly.py", line 144, in runGeospatialAnomaly
    result = model.run(modelInput)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/clamodel.py", line 381, in run
    self._sensorCompute(inputRecord)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/clamodel.py", line 449, in _sensorCompute
    sensor.compute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/engine/__init__.py", line 443, in compute
    return self._region.compute()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/bindings/engine_internal.py", line 1299, in compute
    return _engine_internal.Region_compute(self)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.3.dev0-py2.7-macosx-10.10-intel.egg/nupic/regions/RecordSensor.py", line 296, in compute
    outputs['sourceOut'][:] = self.encoder.getScalars(data)
ValueError: could not broadcast input array from shape (2) into shape (5)
```

**Comment by rhyolight** [comment]
@chetan51 It is not obvious to me what is going wrong here. I don't think that this bug is because of changes made to nupic.geospatial. I think it may be something that's changed in NuPIC internals. I tried running this on different SHAs for this project, all the way back to https://github.com/numenta/nupic.geospatial/commit/708a259857426ecd53eb4c1ffb2c6ab0946c2a6d, which is when I added the time encoder option, and none of them worked. I am certain this was working form me when https://github.com/numenta/nupic.geospatial/commit/708a259857426ecd53eb4c1ffb2c6ab0946c2a6d was committed. 

So I have reverted NuPIC back to https://github.com/numenta/nupic/commit/f52b879fe62ecf2250d378e7c09b41e049a6d0c0, and it works at this point in time. I'm going to open a ticket against NuPIC once I identify the commit that broke this example code.

**Comment by chetan51** [comment]
Sounds like some refactor to nupic encoders broke it?

**Comment by rhyolight** [comment]
Perhaps. I am `git bisect`ing now. I'll let you know what I find.

**Comment by rhyolight** [comment]
@chetan51 Looks like https://github.com/numenta/nupic/commit/e122f23b6e2e0b592af9e953a2414f7fd6d4fd2e is the culprit.

**Comment by rhyolight** [comment]
Once https://github.com/numenta/nupic/issues/1798 is closed, I'll confirm the fix and close this issue.

**Comment by rhyolight** [comment]
Fixed by https://github.com/numenta/nupic/pull/1799.
